version: '3.3'

services:
  node-app:
    build: .
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: always
    ports:
      - "${PORT}:${PORT}"
  db:
    build: ./mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
